version: "3"
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ma_base_de_donnees
      MYSQL_USER: mon_user
      MYSQL_PASSWORD: mon_mot_de_passe
    volumes:
      - ./db-lib:/var/lib/mysql
    ports:
      - 5005:3306
    
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
  
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  
  node:
    build:
      dockerfile: docker/node/Dockerfile
      context: ./
    volumes:
      - ./app:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true   
    tty: true

volumes:
  node_modules:
