version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    depends_on:
      - db
    command: ["npm", "start"]
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ma_base_de_donnees
      MYSQL_USER: mon_user
      MYSQL_PASSWORD: mon_mot_de_passe
    volumes:
      - ./db-lib:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: mon_user
      PMA_PASSWORD: mon_mot_de_passe


# Lancer les Containers (DB):

# docker compose up
