networks:
  twittos_network:
    driver: bridge
    
services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    depends_on:
      - db
    command: ["npm", "start"]
    networks:
      - twittos_network

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ma_base_de_donnees
      MYSQL_USER: mon_user
      MYSQL_PASSWORD: mon_mot_de_passe
    volumes:
      - ./db-lib:/var/lib/mysql
    networks:
      - twittos_network

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80

    networks:
      - twittos_network


# docker compose up
