services:
    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ma_base_de_donnees
            MYSQL_USER: mon_user
            MYSQL_PASSWORD: mon_mot_de_passe
        volumes:
            - ./db-lib:/var/lib/mysql
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: mariadb
            PMA_USER: mon_user
            PMA_PASSWORD: mon_mot_de_passe

#docker compose up
